### ISSUE TITLE
Is it possible to use eyeglass with named parts of an SVG?

### ISSUE THREAD

**Issue by alanhogan** [sass-eyeglass/eyeglass#75]
With SVG, you can refer to a specific part of it using an `id`, which ends up looking like `url(icons.svg#octogon)`. 

However, this confuses Eyeglass and it says it can't find an asset named `icons.svg#octogon`

I will work around this by concat-ing the fragment onto the returned URL from `asset-file()`, but wanted to surface this issue.

**Comment by alanhogan** [comment]
— and ask if there was a recommended way to do this, or if it’s a good potential area for a pull request

**Comment by chriseppstein** [comment]
This is a bug.

**Comment by alanhogan** [comment]
I tried this as a work-around, since it looked like there was an `asset-path()` helper available

```scss
      background-image: url("#{asset-path('z-editor/assets.svg')}#link");
```

Unfortunately this didn’t work, and produced this CSS:

```css
    background-image: url('asset-path("z-editor/assets.svg")#link'); }
```

**Comment by alanhogan** [comment]
In case anyone else has this bug in the mean time: I was able to work around it like so:

```scss
// work-around for
// https://github.com/sass-eyeglass/eyeglass/issues/75
// TODO: Remove this when that bug is fixed
@function url-append($url-string, $append-string) {
  // note: in Sass, indices start at 1. it's a CSS thing.
  @return str-insert($url-string, $append-string, str-length($url-string));
}

// ...

.foo {
  background-image: url-append(asset-url('z-editor/assets.svg'), "#link");
}
```

This will compile to:

```css
  background-image: url(/agent/assets/z-editor/assets.svg#link); }
```
